language: php

php:
  - 7.0

branches:
  only:
    - master
    - dev

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
